# @package _global_
name: EfficientNetb3
arch:
  _target_: srcs.model.model.get_efficentnet_b3_model
  num_classes: 29
loss:
  _target_: srcs.model.loss.focal_loss
optimizer:
  _target_: torch.optim.Adam
  lr: ${learning_rate}
  weight_decay: ${weight_decay}
  amsgrad: true
lr_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: ${scheduler_step_size}
  gamma: ${scheduler_gamma}